name: SSOT CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-and-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Promote updated → blueprints
        run: |
          python scripts/promote_updated.py

      - name: Consolidate SSOT from blueprints
        run: |
          python scripts/ci_consolidate.py

      - name: Validate SSOT invariants
        run: |
          python scripts/ci_validate.py

      - name: Run pre-commit quality checks
        run: |
          pre-commit run --all-files
