repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
  - repo: local
    hooks:
      - id: ssot-validate
        name: SSOT Invariant Validation
        entry: python scripts/ci_validate.py
        language: system
        pass_filenames: false
